# Generated by Django 2.1.3 on 2018-11-20 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20181120_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_details',
            name='AMT_TOTAL',
        ),
        migrations.RemoveField(
            model_name='product_details',
            name='CDIESEL',
        ),
        migrations.RemoveField(
            model_name='product_details',
            name='MISC',
        ),
        migrations.RemoveField(
            model_name='product_details',
            name='OIL',
        ),
        migrations.RemoveField(
            model_name='product_details',
            name='RDIESEL',
        ),
        migrations.RemoveField(
            model_name='product_details',
            name='SUPER',
        ),
        migrations.RemoveField(
            model_name='product_details',
            name='TAX',
        ),
        migrations.RemoveField(
            model_name='product_details',
            name='volCDIESEL',
        ),
        migrations.RemoveField(
            model_name='product_details',
            name='volPlus',
        ),
        migrations.RemoveField(
            model_name='product_details',
            name='volRDIESEL',
        ),
        migrations.RemoveField(
            model_name='product_details',
            name='volSUPER',
        ),
        migrations.RemoveField(
            model_name='product_details',
            name='volUNLD',
        ),
    ]
