# Generated by Django 2.1.3 on 2018-11-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.TextField(null=True)),
                ('produtID', models.IntegerField(null=True)),
                ('Category', models.TextField(null=True)),
            ],
        ),
    ]
