# Generated by Django 2.1.3 on 2018-11-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.TextField(null=True)),
                ('customerAddress', models.TextField(null=True)),
                ('customerPhoneNumber', models.IntegerField(null=True)),
            ],
        ),
    ]
