# Generated by Django 2.1.3 on 2018-11-20 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20181120_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phoneNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='pinCode',
            field=models.IntegerField(null=True),
        ),
    ]
